name: Build thesis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: paperist/texlive-ja:latest

    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: latexmk main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: out/main.pdf